import { BetSchema } from "@/app/dashboard/components/bets-stats";

export type CategoryResult = string;

export const BET_RESULTS = ["Pendente", "Ganha", "Perdida", "Anulada"];

export const MONTH_NAMES = [
  "Janeiro",
  "Fevereiro",
  "Março",
  "Abril",
  "Maio",
  "Junho",
  "Julho",
  "Agosto",
  "Setembro",
  "Outubro",
  "Novembro",
  "Dezembro",
];

export const UNIT_VALUES = [
  {
    value: "3un",
    multiplier: 3,
  },
  {
    value: "2.75un",
    multiplier: 2.75,
  },
  {
    value: "2.5un",
    multiplier: 2.5,
  },
  {
    value: "2un",
    multiplier: 2,
  },
  {
    value: "1.75un",
    multiplier: 1.75,
  },
  {
    value: "1.5un",
    multiplier: 1.5,
  },

  {
    value: "1.25un",
    multiplier: 1.25,
  },
  {
    value: "1un",
    multiplier: 1,
  },
  {
    value: "0.75un",
    multiplier: 0.75,
  },
  {
    value: "0.50un",
    multiplier: 0.5,
  },
];

export const SEED_BETS: BetSchema[] = [
  {
    id: "bet_001",
    userId: "user_abc",
    event: "Flamengo vs Palmeiras",
    market: "Vencedor da Partida",
    category: "Futebol",
    profit: 15.75,
    betValue: 10.0,
    unit: 2,
    odd: 2.58,
    result: "Ganha",
    createdAt: "2025-08-01T10:00:00Z",
  },
  {
    id: "bet_002",
    userId: "user_abc",
    event: "Lakers vs Celtics",
    market: "Total de Pontos (Over/Under)",
    category: "Basquete",
    profit: -20.0,
    betValue: 20.0,
    unit: 2,
    odd: 1.95,
    result: "Perdida",
    createdAt: "2025-08-02T11:30:00Z",
  },
  {
    id: "bet_003",
    userId: "user_abc",
    event: "UFC 300: Poatan vs Pereira",
    market: "Método da Vitória",
    category: "Outro",
    profit: 8.5,
    betValue: 5.0,

    unit: 2,
    odd: 2.7,
    result: "Ganha",
    createdAt: "2025-08-03T14:00:00Z",
  },
  {
    id: "bet_004",
    userId: "user_abc",
    event: "Brasil vs Argentina",
    market: "Vencedor do Set",
    category: "Outro",
    profit: 12.0,
    betValue: 15.0,
    unit: 2,
    odd: 1.8,
    result: "Ganha",
    createdAt: "2025-08-04T16:00:00Z",
  },
  {
    id: "bet_005",
    userId: "user_abc",
    event: "Corinthians vs São Paulo",
    market: "Ambos Marcam",
    category: "Futebol",
    profit: -5.25,
    betValue: 5.25,
    unit: 2,
    odd: 1.9,
    result: "Perdida",
    createdAt: "2025-08-05T09:00:00Z",
  },
  {
    id: "bet_006",
    userId: "user_abc",
    event: "Boston Marathon",
    market: "Vencedor da Corrida",
    category: "Outro",
    profit: 25.0,
    betValue: 10.0,
    unit: 2,
    odd: 3.5,
    result: "Ganha",
    createdAt: "2025-08-06T12:00:00Z",
  },
  {
    id: "bet_007",
    userId: "user_abc",
    event: "Novak Djokovic vs Rafael Nadal",
    market: "Total de Sets",
    category: "Outro",
    profit: 18.25,
    betValue: 15.0,
    unit: 2,
    odd: 2.22,
    result: "Ganha",
    createdAt: "2025-08-07T18:00:00Z",
  },
  {
    id: "bet_008",
    userId: "user_abc",
    event: "Manchester United vs Liverpool",
    market: "Handicap Asiático",
    category: "Futebol",
    profit: -30.0,
    betValue: 30.0,
    unit: 2,
    odd: 2.05,
    result: "Perdida",
    createdAt: "2025-08-08T08:00:00Z",
  },
  {
    id: "bet_009",
    userId: "user_abc",
    event: "NFL: Chiefs vs Packers",
    market: "Vencedor do Jogo",
    category: "Outro",
    profit: 5.5,
    betValue: 10.0,
    unit: 2,
    odd: 1.55,
    result: "Ganha",
    createdAt: "2025-08-09T09:30:00Z",
  },
  {
    id: "bet_010",
    userId: "user_abc",
    event: "F1 Grand Prix: Monza",
    market: "Vencedor da Corrida",
    category: "Outro",
    profit: -10.0,
    betValue: 10.0,
    unit: 2,
    odd: 2.5,
    result: "Perdida",
    createdAt: "2025-08-10T11:00:00Z",
  },
  {
    id: "bet_011",
    userId: "user_abc",
    event: "Argentina vs Uruguai",
    market: "Escanteios (Over/Under)",
    category: "Futebol",
    profit: 22.0,
    betValue: 10.0,
    unit: 2,
    odd: 3.2,
    result: "Ganha",
    createdAt: "2025-08-11T13:00:00Z",
  },
  {
    id: "bet_012",
    userId: "user_abc",
    event: "Golden State vs Cleveland",
    market: "Total de Pontos da Equipe",
    category: "Basquete",
    profit: 10.0,
    betValue: 10.0,
    unit: 2,
    odd: 2.0,
    result: "Ganha",
    createdAt: "2025-08-12T15:00:00Z",
  },
  {
    id: "bet_013",
    userId: "user_abc",
    event: "Paris Olympics: 100m Final",
    market: "Vencedor",
    category: "Outro",
    profit: 1.5,
    betValue: 5.0,

    unit: 2,
    odd: 1.3,
    result: "Ganha",
    createdAt: "2025-08-13T17:00:00Z",
  },
  {
    id: "bet_014",
    userId: "user_abc",
    event: "São Paulo vs Santos",
    market: "Empate Anula Aposta",
    category: "Futebol",
    profit: -1.0,
    betValue: 1.0,

    unit: 2,
    odd: 1.85,
    result: "Perdida",
    createdAt: "2025-08-14T19:00:00Z",
  },
  {
    id: "bet_015",
    userId: "user_abc",
    event: "UFC: Makhachev vs Oliveira",
    market: "Luta vai até o fim?",
    category: "Outro",
    profit: 35.0,
    betValue: 10.0,
    unit: 2,
    odd: 4.5,
    result: "Ganha",
    createdAt: "2025-08-15T20:00:00Z",
  },
  {
    id: "bet_016",
    userId: "user_abc",
    event: "Brasil vs Sérvia",
    market: "Resultado Exato do Set",
    category: "Outro",
    profit: -12.0,
    betValue: 12.0,
    unit: 2,
    odd: 3.0,
    result: "Perdida",
    createdAt: "2025-08-16T21:00:00Z",
  },
  {
    id: "bet_017",
    userId: "user_abc",
    event: "Inter de Milão vs Juventus",
    market: "Total de Gols (Over/Under)",
    category: "Futebol",
    profit: 9.25,
    betValue: 5.0,

    unit: 2,
    odd: 2.85,
    result: "Ganha",
    createdAt: "2025-08-17T22:00:00Z",
  },
  {
    id: "bet_018",
    userId: "user_abc",
    event: "Neymar vs Mbappé: eSports",
    market: "Total de Kills",
    category: "eSports",
    profit: 3.75,
    betValue: 10.0,
    unit: 2,
    odd: 1.38,
    result: "Ganha",
    createdAt: "2025-08-18T23:00:00Z",
  },
  {
    id: "bet_019",
    userId: "user_abc",
    event: "Corinthians vs Fluminense",
    market: "Vencedor da Partida",
    category: "Futebol",
    profit: 18.0,
    betValue: 10.0,
    unit: 2,
    odd: 2.8,
    result: "Ganha",
    createdAt: "2025-08-19T10:00:00Z",
  },
  {
    id: "bet_020",
    userId: "user_abc",
    event: "Los Angeles Rams vs Cowboys",
    market: "Handicap de Pontos",
    category: "Outro",
    profit: -25.0,
    betValue: 25.0,
    unit: 2,
    odd: 1.95,
    result: "Perdida",
    createdAt: "2025-08-20T11:00:00Z",
  },
  {
    id: "bet_021",
    userId: "user_abc",
    event: "F1: Max Verstappen vs Lewis Hamilton",
    market: "Podium Sim/Não",
    category: "Outro",
    profit: 30.0,
    betValue: 15.0,
    unit: 2,
    odd: 3.0,
    result: "Ganha",
    createdAt: "2025-08-21T12:00:00Z",
  },
  {
    id: "bet_022",
    userId: "user_abc",
    event: "Brasil vs EUA",
    market: "Vencedor da Partida",
    category: "Outro",
    profit: 10.5,
    betValue: 10.0,
    unit: 2,
    odd: 2.05,
    result: "Ganha",
    createdAt: "2025-08-22T13:00:00Z",
  },
  {
    id: "bet_023",
    userId: "user_abc",
    event: "Barcelona vs Real Madrid",
    market: "Cartões Amarelos (Mais/Menos)",
    category: "Futebol",
    profit: -15.0,
    betValue: 15.0,
    unit: 2,
    odd: 1.88,
    result: "Perdida",
    createdAt: "2025-08-23T14:00:00Z",
  },
  {
    id: "bet_024",
    userId: "user_abc",
    event: "ATP Finals: Semifinal",
    market: "Vencedor do Jogo",
    category: "Outro",
    profit: 20.0,
    betValue: 10.0,
    unit: 2,
    odd: 3.0,
    result: "Ganha",
    createdAt: "2025-08-24T15:00:00Z",
  },
  {
    id: "bet_025",
    userId: "user_abc",
    event: "CS:GO Major Final",
    market: "Resultado do Round",
    category: "eSports",
    profit: -8.0,
    betValue: 8.0,

    unit: 2,
    odd: 1.95,
    result: "Perdida",
    createdAt: "2025-08-25T16:00:00Z",
  },
  {
    id: "bet_026",
    userId: "user_abc",
    event: "São Paulo vs Atlético-MG",
    market: "Handicap Asiático",
    category: "Futebol",
    profit: -12.5,
    betValue: 12.5,
    unit: 2,
    odd: 2.1,
    result: "Perdida",
    createdAt: "2025-08-26T17:00:00Z",
  },
  {
    id: "bet_027",
    userId: "user_abc",
    event: "Chicago Bulls vs Miami Heat",
    market: "Margem de Vitória",
    category: "Basquete",
    profit: 16.0,
    betValue: 10.0,
    unit: 2,
    odd: 2.6,
    result: "Ganha",
    createdAt: "2025-08-27T18:00:00Z",
  },
  {
    id: "bet_028",
    userId: "user_abc",
    event: "Boxe: Tyson Fury vs Oleksandr Usyk",
    market: "Vencedor da Luta",
    category: "Outro",
    profit: 7.0,
    betValue: 10.0,
    unit: 2,
    odd: 1.7,
    result: "Ganha",
    createdAt: "2025-08-28T19:00:00Z",
  },
  {
    id: "bet_029",
    userId: "user_abc",
    event: "Brasil vs Alemanha",
    market: "Resultado do Set",
    category: "Outro",
    profit: 19.5,
    betValue: 15.0,
    unit: 2,
    odd: 2.3,
    result: "Ganha",
    createdAt: "2025-08-29T20:00:00Z",
  },
  {
    id: "bet_030",
    userId: "user_abc",
    event: "NFL Preseason",
    market: "Total de Touchdowns",
    category: "Outro",
    profit: -22.0,
    betValue: 22.0,
    unit: 2,
    odd: 2.05,
    result: "Perdida",
    createdAt: "2025-08-30T21:00:00Z",
  },
  {
    id: "bet_031",
    userId: "user_abc",
    event: "Flamengo vs Botafogo",
    market: "Ambos Marcam",
    category: "Futebol",
    profit: 3.0,
    betValue: 10.0,
    unit: 2,
    odd: 1.3,
    result: "Ganha",
    createdAt: "2025-08-31T22:00:00Z",
  },
  {
    id: "bet_032",
    userId: "user_abc",
    event: "Real Madrid vs Valencia",
    market: "Vencedor da Partida",
    category: "Futebol",
    profit: 10.0,
    betValue: 5.0,

    unit: 2,
    odd: 3.0,
    result: "Ganha",
    createdAt: "2025-09-01T09:00:00Z",
  },
  {
    id: "bet_033",
    userId: "user_abc",
    event: "LA Clippers vs Denver Nuggets",
    market: "Total de Pontos",
    category: "Basquete",
    profit: -5.0,
    betValue: 5.0,

    unit: 2,
    odd: 1.95,
    result: "Perdida",
    createdAt: "2025-09-02T10:00:00Z",
  },
  {
    id: "bet_034",
    userId: "user_abc",
    event: "UFC: Adesanya vs Costa",
    market: "Método da Vitória",
    category: "Outro",
    profit: 20.0,
    betValue: 10.0,
    unit: 2,
    odd: 3.0,
    result: "Ganha",
    createdAt: "2025-09-03T11:00:00Z",
  },
  {
    id: "bet_035",
    userId: "user_abc",
    event: "Gremio vs Internacional",
    market: "Ambos Marcam",
    category: "Futebol",
    profit: -15.0,
    betValue: 15.0,
    unit: 2,
    odd: 1.8,
    result: "Perdida",
    createdAt: "2025-09-04T12:00:00Z",
  },
  {
    id: "bet_036",
    userId: "user_abc",
    event: "F1: Japanese GP",
    market: "Vencedor da Corrida",
    category: "Outro",
    profit: 5.0,
    betValue: 5.0,

    unit: 2,
    odd: 2.0,
    result: "Ganha",
    createdAt: "2025-09-05T13:00:00Z",
  },
  {
    id: "bet_037",
    userId: "user_abc",
    event: "Serena Williams vs Coco Gauff",
    market: "Vencedor do Jogo",
    category: "Outro",
    profit: 12.0,
    betValue: 10.0,
    unit: 2,
    odd: 2.2,
    result: "Ganha",
    createdAt: "2025-09-06T14:00:00Z",
  },
  {
    id: "bet_038",
    userId: "user_abc",
    event: "NFL: Bengals vs Steelers",
    market: "Total de Pontos",
    category: "Outro",
    profit: -10.0,
    betValue: 10.0,
    unit: 2,
    odd: 1.9,
    result: "Perdida",
    createdAt: "2025-09-07T15:00:00Z",
  },
  {
    id: "bet_039",
    userId: "user_abc",
    event: "São Paulo vs Coritiba",
    market: "Ambos Marcam",
    category: "Futebol",
    profit: 25.0,
    betValue: 15.0,
    unit: 2,
    odd: 2.67,
    result: "Ganha",
    createdAt: "2025-09-08T16:00:00Z",
  },
  {
    id: "bet_040",
    userId: "user_abc",
    event: "Brasil vs Itália",
    market: "Vencedor do Set",
    category: "Outro",
    profit: 8.0,
    betValue: 5.0,

    unit: 2,
    odd: 2.6,
    result: "Ganha",
    createdAt: "2025-09-09T17:00:00Z",
  },
  {
    id: "bet_041",
    userId: "user_abc",
    event: "eSports: League of Legends Final",
    market: "Primeira Torre",
    category: "eSports",
    profit: -2.0,
    betValue: 2.0,

    unit: 2,
    odd: 1.85,
    result: "Perdida",
    createdAt: "2025-09-10T18:00:00Z",
  },
  {
    id: "bet_042",
    userId: "user_abc",
    event: "Flamengo vs Vasco",
    market: "Escanteios (Over)",
    category: "Futebol",
    profit: 18.0,
    betValue: 10.0,
    unit: 2,
    odd: 2.8,
    result: "Ganha",
    createdAt: "2025-09-11T19:00:00Z",
  },
  {
    id: "bet_043",
    userId: "user_abc",
    event: "Chicago Bulls vs Milwaukee Bucks",
    market: "Vencedor da Partida",
    category: "Basquete",
    profit: 3.0,
    betValue: 15.0,
    unit: 2,
    odd: 1.2,
    result: "Ganha",
    createdAt: "2025-09-12T20:00:00Z",
  },
  {
    id: "bet_044",
    userId: "user_abc",
    event: "Boxe: Canelo Alvarez vs Jake Paul",
    market: "Vencedor da Luta",
    category: "Outro",
    profit: -20.0,
    betValue: 20.0,
    unit: 2,
    odd: 2.5,
    result: "Perdida",
    createdAt: "2025-09-13T21:00:00Z",
  },
  {
    id: "bet_045",
    userId: "user_abc",
    event: "Grêmio vs Ceará",
    market: "Handicap Asiático",
    category: "Futebol",
    profit: 15.0,
    betValue: 10.0,
    unit: 2,
    odd: 2.5,
    result: "Ganha",
    createdAt: "2025-09-14T22:00:00Z",
  },
  {
    id: "bet_046",
    userId: "user_abc",
    event: "F1: Singapore GP",
    market: "Podium",
    category: "Outro",
    profit: -10.0,
    betValue: 10.0,
    unit: 2,
    odd: 3.0,
    result: "Perdida",
    createdAt: "2025-09-15T23:00:00Z",
  },
  {
    id: "bet_047",
    userId: "user_abc",
    event: "ATP Finals: Final",
    market: "Vencedor do Torneio",
    category: "Outro",
    profit: 5.0,
    betValue: 5.0,

    unit: 2,
    odd: 2.0,
    result: "Ganha",
    createdAt: "2025-09-16T00:00:00Z",
  },
  {
    id: "bet_048",
    userId: "user_abc",
    event: "EUA vs Canadá",
    market: "Total de Pontos",
    category: "Basquete",
    profit: 20.0,
    betValue: 10.0,
    unit: 2,
    odd: 3.0,
    result: "Ganha",
    createdAt: "2025-09-17T01:00:00Z",
  },
  {
    id: "bet_049",
    userId: "user_abc",
    event: "UFC: Luta Principal",
    market: "Método da Vitória",
    category: "Outro",
    profit: 1.0,
    betValue: 5.0,

    unit: 2,
    odd: 1.2,
    result: "Ganha",
    createdAt: "2025-09-18T02:00:00Z",
  },
  {
    id: "bet_050",
    userId: "user_abc",
    event: "Corinthians vs Ceará",
    market: "Cartões Amarelos (Over)",
    category: "Futebol",
    profit: -8.0,
    betValue: 8.0,

    unit: 2,
    odd: 1.9,
    result: "Perdida",
    createdAt: "2025-09-19T03:00:00Z",
  },
  {
    id: "bet_051",
    userId: "user_abc",
    event: "NFL: Super Bowl",
    market: "Vencedor",
    category: "Outro",
    profit: 12.0,
    betValue: 10.0,
    unit: 2,
    odd: 2.2,
    result: "Ganha",
    createdAt: "2025-09-20T04:00:00Z",
  },
  {
    id: "bet_052",
    userId: "user_abc",
    event: "F1: Final da Temporada",
    market: "Campeão da Temporada",
    category: "Outro",
    profit: 15.0,
    betValue: 5.0,

    unit: 2,
    odd: 4.0,
    result: "Ganha",
    createdAt: "2025-09-21T05:00:00Z",
  },
  {
    id: "bet_053",
    userId: "user_abc",
    event: "Brasil vs Rússia",
    market: "Total de Sets (Over)",
    category: "Outro",
    profit: -5.0,
    betValue: 5.0,

    unit: 2,
    odd: 1.85,
    result: "Perdida",
    createdAt: "2025-09-22T06:00:00Z",
  },
  {
    id: "bet_054",
    userId: "user_abc",
    event: "Barcelona vs Atlético de Madrid",
    market: "Ambos Marcam",
    category: "Futebol",
    profit: 10.0,
    betValue: 5.0,

    unit: 2,
    odd: 3.0,
    result: "Ganha",
    createdAt: "2025-09-23T07:00:00Z",
  },
  {
    id: "bet_055",
    userId: "user_abc",
    event: "League of Legends Finals",
    market: "Vencedor do Jogo",
    category: "eSports",
    profit: -2.0,
    betValue: 2.0,

    unit: 2,
    odd: 1.9,
    result: "Perdida",
    createdAt: "2025-09-24T08:00:00Z",
  },
  {
    id: "bet_056",
    userId: "user_abc",
    event: "São Paulo vs Palmeiras",
    market: "Número de Gols (Over)",
    category: "Futebol",
    profit: 25.0,
    betValue: 10.0,
    unit: 2,
    odd: 3.5,
    result: "Ganha",
    createdAt: "2025-09-25T09:00:00Z",
  },
  {
    id: "bet_057",
    userId: "user_abc",
    event: "Lakers vs Miami Heat",
    market: "Handicap de Pontos",
    category: "Basquete",
    profit: 8.0,
    betValue: 10.0,
    unit: 2,
    odd: 1.8,
    result: "Ganha",
    createdAt: "2025-09-26T10:00:00Z",
  },
  {
    id: "bet_058",
    userId: "user_abc",
    event: "Boxe: Luta do Ano",
    market: "Número de Rounds",
    category: "Outro",
    profit: -1.0,
    betValue: 1.0,

    unit: 2,
    odd: 1.5,
    result: "Perdida",
    createdAt: "2025-09-27T11:00:00Z",
  },
  {
    id: "bet_059",
    userId: "user_abc",
    event: "Brasil vs Argentina",
    market: "Vencedor da Partida",
    category: "Outro",
    profit: 5.0,
    betValue: 5.0,

    unit: 2,
    odd: 2.0,
    result: "Ganha",
    createdAt: "2025-09-28T12:00:00Z",
  },
  {
    id: "bet_060",
    userId: "user_abc",
    event: "F1: Brazilian GP",
    market: "Piloto Vencedor",
    category: "Outro",
    profit: 15.0,
    betValue: 10.0,
    unit: 2,
    odd: 2.5,
    result: "Ganha",
    createdAt: "2025-09-29T13:00:00Z",
  },
  {
    id: "bet_061",
    userId: "user_abc",
    event: "Real Madrid vs Barcelona",
    market: "Resultado Exato",
    category: "Futebol",
    profit: -12.0,
    betValue: 12.0,
    unit: 2,
    odd: 8.0,
    result: "Perdida",
    createdAt: "2025-09-30T14:00:00Z",
  },
];
